### ISSUE TITLE
Update macadmin.info to use https

### ISSUE THREAD

**Issue by smashism** [macadmininfo/macadmininfo.github.io#30]
ICYMI this is built into GitHub Pages settings now: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Once just needs to update the A hostname records with the DNS provider: https://help.github.com/articles/setting-up-an-apex-domain/

<3

**Comment by macadmininfo** [comment]
Yeah, sorry this took so long to get to.

Done.
