### ISSUE TITLE
Update reading list book on mac admin site 

### ISSUE THREAD

**Issue by rwannn** [macadmininfo/macadmininfo.github.io#45]
Hi, Rosa from Peachpit Press. We released a new edition of the macOS Support Essentials book. Can you please update the book to the new edition? Here are the details: 

Title: macOS Support Essentials 12 - Apple Pro Training Series: Supporting and Troubleshooting macOS Monterey
Authors: Adam Karneboge, Benjamin G. Levy, Steve Leebove
Link: https://www.peachpit.com/store/macos-support-essentials-12-apple-pro-training-series-9780137696444

Contact me at rosa.wan@pearson.com if you have any questions - thanks!

**Comment by marczak** [comment]
Added! Thanks for the info.

**Comment by rwannn** [comment]
Awesome, thank you!
________________________________
